import { NextResponse } from "next/server";
import JSZip from "jszip";
import { supabaseFromCookies } from "@/lib/google-oauth";

export const runtime = "nodejs";
export const maxDuration = 60;

const MAX_BYTES = 4 * 1024 * 1024;
const MAX_CHARS = 150000;
const ALLOWED = [".txt", ".md", ".csv", ".docx", ".pdf"];
const EXTRACT_MODELS = ["gemini-3.8-flash", "gemini-flash-latest", "gemini-3.1-pro-preview"];

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function pdfParseExtract(buffer: Buffer): Promise<{ text: string; error: string }> {
  try {
    const mod: any = await import("pdf-parse");
    const PDFParseCtor = mod.PDFParse || mod.default?.PDFParse || mod.default;
    if (!PDFParseCtor) return { text: "", error: "PDF engine unavailable" };
    const parser = new PDFParseCtor({ data: buffer });
    try {
      const result = await parser.getText();
      return { text: String(result?.text || ""), error: "" };
    } finally {
      try { parser.destroy(); } catch { /* ignore */ }
    }
  } catch (e: any) {
    return { text: "", error: e?.message || "pdf-parse failed" };
  }
}

async function aiExtractPdf(buffer: Buffer): Promise<{ text: string; detail: string }> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) return { text: "", detail: "GEMINI_API_KEY is not configured" };
  let binary = "";
  for (let i = 0; i < buffer.length; i += 0x8000) binary += String.fromCharCode(...buffer.subarray(i, i + 0x8000));
  const data = btoa(binary);
  const prompt = [
    `Extract ALL text from this PDF document verbatim and completely.`,
    `Preserve the document structure:`,
    `- Keep every numbered section, clause number, heading and sub-heading exactly as written.`,
    `- Keep tables as readable text (one row per line, cells separated by " | ").`,
    `- If the pages are scanned images, read the text from the images and transcribe it accurately.`,
    `- Do not summarize, reword, translate, or omit anything.`,
    `Return only the extracted text, nothing else.`,
  ].join("\n");
  const details: string[] = [];
  for (let m = 0; m < EXTRACT_MODELS.length; m++) {
    const model = EXTRACT_MODELS[m];
    const retries = m === 0 ? 2 : 1;
    for (let attempt = 0; attempt < retries; attempt++) {
      if (attempt > 0) await sleep(3000);
      try {
        const controller = new AbortController();
        const timer = setTimeout(() => controller.abort(), 20000);
        const res = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              contents: [{ role: "user", parts: [{ text: prompt }, { inlineData: { mimeType: "application/pdf", data } }] }],
              generationConfig: { temperature: 0.2, maxOutputTokens: 16384 },
            }),
            signal: controller.signal,
          }
        );
        clearTimeout(timer);
        if (!res.ok) {
          const msg = `${model}: HTTP ${res.status} ${(await res.text()).slice(0, 150)}`;
          details.push(msg);
          if (res.status === 503 || res.status === 429 || res.status === 500) continue;
          break;
        }
        const json = await res.json();
        const blocked = json.promptFeedback?.blockReason;
        const text = (json.candidates?.[0]?.content?.parts || []).map((p: any) => p.text || "").join("").trim();
        if (text) return { text, detail: `generated by ${model}` };
        details.push(`${model}: empty output${blocked ? ` (blocked: ${blocked})` : ""}`);
      } catch (e: any) {
        details.push(`${model}: ${e?.message || "error"}`);
      }
    }
  }
  return { text: "", detail: details.join(" | ") || "no models attempted" };
}

function decodeXmlEntities(s: string): string {
  return s
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&#\d+;/g, (m) => {
      const code = parseInt(m.slice(2, -1), 10);
      try { return String.fromCodePoint(code); } catch { return " "; }
    });
}

function stripDocxXml(xml: string): string {
  return decodeXmlEntities(
    xml
      .replace(/<w:tab[^>]*\/>/g, " ")
      .replace(/<w:br[^>]*\/>/g, "\n")
      .replace(/<\/w:p>/g, "\n")
      .replace(/<\/w:tr>/g, "\n")
      .replace(/<[^>]+>/g, "")
  )
    .split(/\r?\n/)
    .map((l) => l.replace(/\s+/g, " ").trim())
    .filter(Boolean)
    .join("\n");
}

export async function POST(req: Request) {
  const supabase = await supabaseFromCookies();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const form = await req.formData().catch(() => null);
  const file = form?.get("file");
  if (!(file instanceof File)) return NextResponse.json({ error: "No file provided." }, { status: 400 });
  if (file.size > MAX_BYTES) return NextResponse.json({ error: "File must be 4MB or smaller." }, { status: 413 });
  if (file.size === 0) return NextResponse.json({ error: "File is empty." }, { status: 400 });

  const name = file.name.toLowerCase();
  const ext = (name.match(/\.[a-z0-9]+$/i) || [])[0]?.toLowerCase() || "";
  if (!ALLOWED.includes(ext)) {
    return NextResponse.json({ error: "Supported formats: TXT, DOCX, PDF." }, { status: 415 });
  }

  const buffer = Buffer.from(await file.arrayBuffer());
  let text = "";
  let detail = "";

  if (ext === ".pdf") {
    const parsed = await pdfParseExtract(buffer);
    if (parsed.text.trim().length >= 40) {
      text = parsed.text.trim();
      detail = "extracted with the PDF reader";
    } else {
      const ai = await aiExtractPdf(buffer);
      if (ai.text.trim().length >= 40) {
        text = ai.text.trim();
        detail = ai.detail;
      } else {
        detail = ai.detail || (parsed.error ? `pdf-parse: ${parsed.error}` : "no text found");
      }
    }
  } else if (ext === ".docx") {
    try {
      const zip = await JSZip.loadAsync(buffer);
      const entry = zip.file("word/document.xml");
      if (!entry) return NextResponse.json({ error: "This DOCX has no readable content." }, { status: 400 });
      const xml = await entry.async("string");
      text = stripDocxXml(xml);
    } catch {
      return NextResponse.json({ error: "Could not read this DOCX file. Try saving it as PDF or copy the text into a TXT file.", detail }, { status: 422 });
    }
  } else {
    try {
      text = buffer.toString("utf8").replace(/^\uFEFF/, "");
    } catch {
      return NextResponse.json({ error: "Could not read this file. Copy the text into a TXT file.", detail }, { status: 422 });
    }
  }

  text = text.replace(/\r\n/g, "\n").replace(/[ \t]+\n/g, "\n").replace(/\n{3,}/g, "\n\n").trim();
  if (!text) {
    return NextResponse.json({
      error: "No text could be extracted from this file.",
      detail: `The AI could not read this document. ${detail || "Unknown reason"}`,
    }, { status: 422 });
  }

  const truncated = text.length > MAX_CHARS;
  if (truncated) text = text.slice(0, MAX_CHARS) + "\n[… remainder truncated …]";

  return NextResponse.json({
    text,
    fileName: file.name,
    charCount: text.length,
    truncated,
  });
}